services:
  - type: web
    name: cgpa-project
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn cgpa_project.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: TWILIO_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_PHONE_NUMBER
        sync: false
    databases:
      - name: db
        databaseName: cgpa_db
        plan: free
